### ISSUE TITLE
Request to `/api/v1/chat.syncMessages` fails with `The \"lastUpdate\" query parameter must be a valid date.`

### ISSUE THREAD

**Issue by svenseeberg** [RocketChat/Rocket.Chat.ReactNative#6057]
### Description:

The app sends requests to `/api/v1/chat.syncMessages?roomId=ROOMID&lastUpdate=undefined`. The back end returns an error:

```
"level":35,"time":"2024-12-13T19:57:58.602Z","pid":1040862,"hostname":"rocketchat","name":"API","method":"GET","url":"/api/v1/chat.syncMessages?roomId=ROOMID&lastUpdate=undefined","userId":"USERID","userAgent":"RC Mobile; android 9; v4.55.0 (70132)","host":"rc.example.com","remoteIP":"USERIP","err":{"type":"errorClass","message":"The \"lastUpdate\" query parameter must be a valid date. [error-roomId-param-invalid]","stack":"Error: The \"lastUpdate\" query parameter must be a valid date. [error-roomId-param-invalid]\n    at app/api/server/v1/chat.ts:91:11\n    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at app/api/server/api.ts:649:39\n    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":"error-roomId-param-invalid","reason":"The \"lastUpdate\" query parameter must be a valid date.","errorType":"Meteor.Error"},"status":400,"responseTime":2,"msg":"The \"lastUpdate\" query parameter must be a valid date. [error-roomId-param-invalid]"}
```

### Environment Information:

- Rocket.Chat Server Version: 6.13.1
- Rocket.Chat App Version: v4.55.0 and others
- Device Name: 
- OS Version: Android/iOS all versions

### Steps to reproduce:

I cannot provide exact steps to reproduce.

### Expected behavior:

The app should always send a date in lastUpdate. Alternatively, the server should accept undefined lastUpdate.

### Actual behavior:

N/A

### Additional context:

We have some reports by users that they click on push notifications but the message does not load in channels. We suspect that this could be related.

**Comment by diegolmello** [comment]
@OtavioStasiak could it be related to https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5992?

**Comment by OtavioStasiak** [comment]
I am not sure,  but it could be related to the recent changes made to `load` and `getLastUpdate`. I will test it here and try to reproduce.

**Comment by anicoa** [comment]
Any news on this? We have this problem also after upgrading to 7.x

**Comment by Rohit3523** [comment]
Can you share more information about this issue like when this error occurred and steps so I can give it a try.
It would be great if anyone is ready to provide me your workspace url because it's a time taking process to setup one 😔

**Comment by OtavioStasiak** [comment]
I couldn't reproduce this issue.
@svenseeberg is the error happening in some specific case (EX: just if I create new room)?
@anicoa could you provide more information about it?

**Comment by Rohit3523** [comment]
Reopened 👀

**Comment by diegolmello** [comment]
As I said on #6250, that PR could fix the issue theoretically.
I was not able to reproduce the issue, so things are harder to confirm.

Just submitted a beta version to the stores.
Can you test it for a few days before it goes public?

Rocket.Chat iOS: 4.59.0.76580 (https://testflight.apple.com/join/3gcYeoMr)
Rocket.Chat Android: 4.59.0.76581 (https://play.google.com/store/apps/details?id=chat.rocket.android)

Reopening this issue until we have a confirmation from your side.
Let me know if you have any questions.

**Comment by anicoa** [comment]
Don't know if its related: often threads arent shown correctly (three different servers).

I can not see, that it is a thread. If I open a new thread, all the messages are shown.

Regarding lastUpdate we will check server-logs

**Comment by anicoa** [comment]
Regarding lastUpdate=undefined: i greped our log files. We have only one occurence (RC Mobile; ios 18.4; v4.51.0 (64829)) for the last days. So I guess it's solved?

**Comment by diegolmello** [comment]
@anicoa If your workspace is 7.1+, it's not going to make that request like that
```
/api/v1/chat.syncMessages?roomId=ROOMID&lastUpdate=undefined
```

It should appear like this
```
/api/v1/chat.syncMessages?roomId=ROOMID&next=NEXT&count=50&type=UPDATED"
/api/v1/chat.syncMessages?roomId=ROOMID&next=NEXT&count=50&type=DELETED"
```

**Comment by ajibarra** [comment]
I have experienced this for a while. Today I updated server to latest version and still happens.

Platform: iOS
App version: 4.59.0.77344
Workspace version: 7.5.0

**Comment by Den4ik92** [comment]
I know how to repeat the bug!

Requirements:

1. A running server
2. Two users in the chat
3. A running web or desktop client (with user 1)
4. A running React Native client in the emulator (with user 2)
5.  A direct message (DM) between the two users (or possibly a shared channel—unclear), as well as the chat or room ID (if using the browser client, you can get it from the address bar)
6. An HTML document with a deeplink (simulating push notification navigation) to navigate to your existing DM chat, e.g.:
rocketchat://room?host=http://192.168.1.2&rid=ROOM_ID (Replace ROOM_ID with your actual room/channel ID; each user will have a different one. See above for where to find it.)
P.S. You need to copy this HTML file to the emulator.

Steps to Reproduce:

1. Open the same chat (the one specified in step 6) on both the emulator and the desktop client.
2. Send a message from the desktop client and make sure everything works and the message appears on both clients.
3. Without closing the chat, minimize the Rocket.Chat app on the emulator.
4. From the desktop client, send another message to the mobile user.
5. On the emulator, open the HTML document with the deeplink in the browser and follow the link to navigate to the chat.
The chat should open, but the last message will not load (even though it appears in the chat list preview).


P.S. Sometimes it doesn't reproduce on the first try. All checks were done on the single-server branch.

The issue is somewhere in /app/lib/methods/subscriptions/rooms.ts,
specifically in the debouncedUpdate function. However, it's not only about that function — I haven't yet figured out how to fix it without breaking the app.

**Comment by diegolmello** [comment]
Hey @Den4ik92.
Thanks a lot for working on the reproducible steps!
I'm going to try them now.

Btw you can use this on terminal to dispatch a deep link to the simulator instead of the HTML doc :)

iOS: `xcrun simctl openurl booted rocketchat://room\?host=${server}\&rid=${rid}`
Android: `adb shell am start -a android.intent.action.VIEW -d "rocketchat://room?host=${server}&rid=${rid}"`

**Comment by Den4ik92** [comment]
Hi, thanks for the tip)

**Comment by diegolmello** [comment]
@Den4ik92 I was not able to reproduce it a single time 😕

**Comment by Den4ik92** [comment]
I forgot to clarify, it worked for me on an android emulator

**Comment by diegolmello** [comment]
I tried on both, just to be sure

**Comment by Den4ik92** [comment]
I recorded a video of how this happens to me, it repeats itself every time. [https://drive.google.com/file/d/1paRi7hYzfbKE7k2F5CiHmqWEYytTpGqF/view?usp=drive_link](url)

**Comment by Den4ik92** [comment]
the problem is in the debouncedUpdate function, when opening a chat, 2 calls to the debouncedUpdate function are made to update the channel subscription, and the first of them is simply overwritten, since they have the same key.

**Comment by diegolmello** [comment]
@Den4ik92 

Do two things: 

- remove the protocol from your host's deep link
`rocketchat://room?host=http://192.168.1.2&rid=room_id` -> `rocketchat://room?host=192.168.1.2&rid=room_id/`

- Add console.log on debounced updates to understand what's being triggered and overwritten

**Comment by Den4ik92** [comment]
Hi, I went further and found what the problem. Is in the app/lib/methods/subscriptions/roms.ts file on line 211 there is an incorrect condition `if (tmp.lastMessage && subscribedRoom !== tmp.rid) {` which was never executed, I changed it to `if (tmp.lastMessage && subscribedRoom === tmp.rid) {` and everything start worked as it should

**Comment by diegolmello** [comment]
@Den4ik92 the condition is correct.

- subscriptions/rooms has the websocket events from subscription/room collections
- subscriptions/room has the websocket events from messages collection

When a message is received, both sides are going to trigger an event.
- `subs/rooms` because `room.lastMessage` changes
- `subs/room` because there's a new message

That condition checks if the app is focused on the room already and just ignores the event for `subs/rooms`, since the same event is going to be dispatched on `subs/room`.
We do that to avoid deadlock and to save CPU.

**Comment by Den4ik92** [comment]
I understand, thanks for the explanation, I'll go look further

**Comment by Den4ik92** [comment]
@diegolmello I think I understood how and why this bug occurs:
1) The room must be open (active subscription to the room) which we will then open via deeplink
2) The application must be minimized!!!!
3) Send a message to the mobile client only after we minimize the mobile client.
--What is happening:
3-1) the handleMessageReceived function is executed but the logic inside it does not work, since the setTimeout() function does not work in the background when the application is minimized)

4) Open the room via deeplink
the execution of the handleMessageReceived logic does not occur
--What is happening:
4-1) Unsubscribing from a room to which you were previously subscribed
4-2) New subscription to the room

P.S. For now, I have solved the problem for myself by removing setTimeout() from handleMessageReceived. I understand that this will load the processor when receiving messages in a subscribed chat, but receiving messages is more important to me now.

Perhaps there is a more correct solution, I would be very grateful for a hint))

**Comment by diegolmello** [comment]
@Den4ik92 Gave it a try on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6485
I wrote a quick load test with [Maestro](https://maestro.dev/) to understand the difference, but I was not able to reproduce in none of the scenarios.

While I agree `setTimeout` won't work properly in background, the content inside of it is going to be triggered after 1 second. I wonder if that's enough time to cause any issues, but I don't doubt it.
That part of the code was written a long time ago, before Hermes or JSI, so perhaps removing the setTimeout won't impact so much, but we need to test it properly.

I'm going to give it another shot tomorrow. I think `goRoom` can also be the issue here, since it's dispatching a navigation to RoomView even though it's already positioned in the correct room.

**Comment by diegolmello** [comment]
Merged #6492, which removes the window as @Den4ik92 proposed, but also fixes some navigation issues, like when opening the app from push notification.
I'm going to release a beta later today.
Let's keep an eye on how it goes and we close this issue after we're sure it's fixed.

**Comment by Den4ik92** [comment]
This is great, thanks for the feedback. I will definitely check it out. 
The bug has stopped appearing in most cases. But there is one case that still remains: 
1) open a chat. 
2) minimize the application and wait for some time until the background processes are disabled (most likely, Android optimization mechanisms are triggered). 
3) send a message to the chat opened in the application. 4) open a chat from a notification.

The chat is loaded but without a new message.
In order for the messages to load, you have to completely close and reopen the application.

**Comment by diegolmello** [comment]
@Den4ik92 I didn't get.
Did you cherry-picked commits and tried on your app or what?
This is not available on stores yet.

**Comment by Den4ik92** [comment]
No, I compiled the application from the current version 4.61.0.1 with my fix and without any navigation changes and tested it on my phone.

**Comment by Den4ik92** [comment]
Sorry, I didn't fully understand, we'll wait for the latest release)

**Comment by Rei-Tw** [comment]
Hello,

What's the current state of this issue ?

I'm running version 4.73.1.109040, this bug exists since years now and definetly makes me want to uninstall this app and switch to another solution.

Each time I'm running the client It stays in "Updating" state and doesn't update my messages unless I clear the cache.

**Comment by Den4ik92** [comment]
You can try fix this issues on your server. Its help for me.
https://github.com/RocketChat/Rocket.Chat/issues/15028#issue-470801275
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4012#issue-1192202655
